---
driver:
  name: vagrant
  customize:
      memory: 1024
      cpus: 2
      ioapic: 'on'

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.4

suites:
  - name: default
    run_list:
      - recipe[posty::default]
    attributes:
        mysql:
            server_root_password: TESTKITCHENTEST
        posty:
            db:
                dbpass: TESTKITCHENTEST
            roundcube:
                dbpass: TESTKITCHENTEST
  - name: minimal
    run_list:
      - recipe[posty::default]
    attributes:
        mysql:
            server_root_password: TESTKITCHENTEST
        posty:
            db:
                dbpass: TESTKITCHENTEST
            roundcube:
                dbpass: TESTKITCHENTEST
            clamav:
                install: false
            spamassassin:
                install: false
